version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: wtbooking-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: wtbooking-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
